build-and-publish-latest:
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main' # Running this job only for main branch

  steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.1.12
      with:
        github-token: ${{ secrets.TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: website # Provide only Docker image name, tag will be automatically set to latest
        dockerfile: Dockerfile